[project]
name = "gestor-asistencias"
version = "0.1.0"
description = "Django application for managing employee attendance and schedules"
dependencies = [
    "django",
    "psycopg[binary]",
    "pyyaml",
    "gunicorn",
]

[tool.uv]
dev-dependencies = [
    "playwright",
]